In [9]:
import pandas as pd
import numpy as np

data_set = pd.DataFrame({
    "Order_ID":[101,102,103,104,105,106,107,108,109,110,111,111],
    "Customer":[
        "Ali","Sara","John","Emma",
        "Ali","Fatima","David",
        np.nan,"Kabir","John",
        "Emma","Emma"
    ],
    "City":[
        "Delhi","Delhi","Mumbai",
        "Pune","Delhi","Mumbai",
        "Lucknow","Delhi",
        "Pune","Mumbai",
        "Lucknow","Lucknow"
    ],
    "Category":[
        "Laptop","Phone","Laptop",
        "Phone","Tablet","Laptop",
        "Phone","Tablet",
        "Laptop","Phone",
        "Tablet","Tablet"
    ],
    "Revenue":[
        70000,30000,80000,
        25000,40000,90000,
        20000,np.nan,
        60000,45000,
        30000,30000
    ],
    "Quantity":[
        2,3,1,2,4,2,1,5,2,3,2,2
    ],
    "Rating":[
        4.8,4.3,4.9,
        4.1,4.5,4.8,
        3.9,4.2,4.6,4.4,
        np.nan,4.0
    ],
    "Payment":[
        "UPI","Cash","Card",
        "UPI","Card","Cash",
        "UPI","Card",
        "Cash","UPI",
        "Card","Card"
    ],
    "Order_Date":[
        "2025-01-10",
        "2025-01-22",
        "2025-02-11",
        "2025-02-25",
        "2025-03-12",
        "2025-03-29",
        "2025-04-14",
        "2025-04-25",
        "2025-05-18",
        "2025-06-05",
        "2025-06-15",
        "2025-06-15"
    ]
})
df=data_set.copy()
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [10]:
#1
df.head(5)
df

,Order_ID,Customer,City,Category,Revenue,Quantity,Rating,Payment,Order_Date
0,101,Ali,Delhi,Laptop,70000.0,2,4.8,UPI,2025-01-10
1,102,Sara,Delhi,Phone,30000.0,3,4.3,Cash,2025-01-22
2,103,John,Mumbai,Laptop,80000.0,1,4.9,Card,2025-02-11
3,104,Emma,Pune,Phone,25000.0,2,4.1,UPI,2025-02-25
4,105,Ali,Delhi,Tablet,40000.0,4,4.5,Card,2025-03-12
5,106,Fatima,Mumbai,Laptop,90000.0,2,4.8,Cash,2025-03-29
6,107,David,Lucknow,Phone,20000.0,1,3.9,UPI,2025-04-14
7,108,NaN,Delhi,Tablet,NaN,5,4.2,Card,2025-04-25
8,109,Kabir,Pune,Laptop,60000.0,2,4.6,Cash,2025-05-18
9,110,John,Mumbai,Phone,45000.0,3,4.4,UPI,2025-06-05
10,111,Emma,Lucknow,Tablet,30000.0,2,NaN,Card,2025-06-15
11,111,Emma,Lucknow,Tablet,30000.0,2,4.0,Card,2025-06-15

In [11]:
#2
df.shape
#rows:12,columns: 9

(12, 9)

In [12]:
#3
df.columns
#the colmns are - (['Order_ID', 'Customer', 'City', 'Category', 'Revenue', 'Quantity',
       #'Rating', 'Payment', 'Order_Date'])

Index(['Order_ID', 'Customer', 'City', 'Category', 'Revenue', 'Quantity',
       'Rating', 'Payment', 'Order_Date'],
      dtype='object')

In [13]:
#4
df.info()
#df.info(), tells us that
#rows-12
#columns-9
#Data type of columns revenue , rating- float 64,decimal
#data type of order_id and quantity column- int 64,integer
# order_date column is date time formatted already so dont need to convert it
#data type of remaining columns are of object type
# in summary we have - dtypes: datetime64[ns](1), float64(2), int64(2), object(4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    12 non-null     int64
 1   Customer    11 non-null     object
 2   City        12 non-null     object
 3   Category    12 non-null     object
 4   Revenue     11 non-null     float64
 5   Quantity    12 non-null     int64
 6   Rating      11 non-null     float64
 7   Payment     12 non-null     object
 8   Order_Date  12 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 996.0+ bytes

In [15]:
#5
df.isna().sum()
#customer,revenue and rating columns , each have one missing value
#Remove the customer row that has nan bcz its revenue column is also nan so it cannot give us a better understanding of data

Order_ID      0
Customer      1
City          0
Category      0
Revenue       1
Quantity      0
Rating        1
Payment       0
Order_Date    0
dtype: int64

In [16]:
#6
df['Order_ID'].duplicated().sum()
df[df['Order_ID'].duplicated()]
#df.loc[[10,11]]
#our dataset has one duplicate with rating oclumn filled, lets extract this info.
df['Rating']=df['Rating'].fillna(4.0)
#df.loc[[10,11]]
df.duplicated().sum()
#7
df=df.drop_duplicates()
df.tail()
#there were a duplicate that cannot be detected by just pandas fn so we inspect it , 
#find the useful info ,extract it , use it
#and then remove the duplicate that can be detected bty pandad function

,Order_ID,Customer,City,Category,Revenue,Quantity,Rating,Payment,Order_Date
6,107,David,Lucknow,Phone,20000.0,1,3.9,UPI,2025-04-14
7,108,NaN,Delhi,Tablet,NaN,5,4.2,Card,2025-04-25
8,109,Kabir,Pune,Laptop,60000.0,2,4.6,Cash,2025-05-18
9,110,John,Mumbai,Phone,45000.0,3,4.4,UPI,2025-06-05
10,111,Emma,Lucknow,Tablet,30000.0,2,4.0,Card,2025-06-15

In [20]:
df.isna().sum()
df=df.dropna()
df
#better approach is removing na or filling na making decision after dealing with duplicates

,Order_ID,Customer,City,Category,Revenue,Quantity,Rating,Payment,Order_Date
0,101,Ali,Delhi,Laptop,70000.0,2,4.8,UPI,2025-01-10
1,102,Sara,Delhi,Phone,30000.0,3,4.3,Cash,2025-01-22
2,103,John,Mumbai,Laptop,80000.0,1,4.9,Card,2025-02-11
3,104,Emma,Pune,Phone,25000.0,2,4.1,UPI,2025-02-25
4,105,Ali,Delhi,Tablet,40000.0,4,4.5,Card,2025-03-12
5,106,Fatima,Mumbai,Laptop,90000.0,2,4.8,Cash,2025-03-29
6,107,David,Lucknow,Phone,20000.0,1,3.9,UPI,2025-04-14
8,109,Kabir,Pune,Laptop,60000.0,2,4.6,Cash,2025-05-18
9,110,John,Mumbai,Phone,45000.0,3,4.4,UPI,2025-06-05
10,111,Emma,Lucknow,Tablet,30000.0,2,4.0,Card,2025-06-15

In [21]:
#8
df.dtypes
'''
Order_ID               int64
Customer              object
City                  object
Category              object
Revenue              float64
Quantity               int64
Rating               float64
Payment               object
Order_Date    datetime64[ns]
'''

'\nOrder_ID               int64\nCustomer              object\nCity                  object\nCategory              object\nRevenue              float64\nQuantity               int64\nRating               float64\nPayment               object\nOrder_Date    datetime64[ns]\n'

In [22]:
#9
df['City'].unique()
df['City'].nunique()
#our dataset has cities - ['Delhi', 'Mumbai', 'Pune', 'Lucknow']
#total 4 unique cities

4

In [23]:
#10
df['Customer'].nunique()
#7 unique customer , rows are 12 that means some pople whether have same name or ordered more than one product

7

In [24]:
#11
df[['Revenue','Rating','Quantity']].describe()
# rating:avg=4.4,max=4.9,min
#revenue:avg=49000,max = 90000,min=20000
#quantity=11

            Revenue     Rating   Quantity
count     10.000000  10.000000  10.000000
mean   49000.000000   4.430000   2.200000
std    24585.451886   0.352924   0.918937
min    20000.000000   3.900000   1.000000
25%    30000.000000   4.150000   2.000000
50%    42500.000000   4.450000   2.000000
75%    67500.000000   4.750000   2.750000
max    90000.000000   4.900000   4.000000

In [25]:
#12
df.describe(include='object')

       Customer   City Category Payment
count        10     10       10      10
unique        7      4        3       3
top         Ali  Delhi   Laptop     UPI
freq          2      3        4       4

In [26]:
#13
df['Payment'].value_counts()
#UPI and Card are most widely used payment method

Payment
UPI     4
Cash    3
Card    3
Name: count, dtype: int64

In [27]:
#14
df['Category'].value_counts()
#Tablet is least commom category

Category
Laptop    4
Phone     4
Tablet    2
Name: count, dtype: int64

In [28]:
#15
df['Revenue'].mean()
#49000 is average revenue

np.float64(49000.0)

In [30]:
#16
#The qulaity of data set is decent as it concludes the colummns that can help analyse and predict to take decision 
#for the better sake of our company such as - Payment method,revenue ,quantity,rating etc. By correlaitng these coluns with each 
#each other we can extract good innsights and helpful info from this data
#but if we add a column to ask user do they like our product on scale (good, bad , excellent) so they will be more friendly and less frutrating for users then click on stars.
#and then we can scale numbers of all category like for good 2.5  to 3.5 , for bad 0 to 3.4 and for excellent 3.6 to 5

In [33]:
#17I wil clean first-Revenue (bcz it tells the profit ,loss of our company), rating per prodct and per .17

In [43]:
#18
df.groupby('Category')['Revenue'].sum().idxmax()
# Laptop generates total highest revenue
df.groupby('Category')['Rating'].mean()
#all products of our company performs on similar avg ratinnf from 4.1 to 4.2
df.groupby('Payment')['Revenue'].sum()
#lowest revenue from card and highest revenue from cash, we should make ouf cash procedure more flexible and work on encouraging customer pay using card with ease
df.groupby('Customer')['Revenue'].sum().idxmax()
#John contributes good amount in our revenue , we should give him some offer for his next order
df.groupby('Category')['Quantity'].sum()
#Phones from our company ar sold most
df.groupby('City')['Revenue'].sum().idxmax()
#mumbai needs our compny to be more flexible i serives like delivery , price etc as it generates good amount of revenue

'Mumbai'